# 모두를 위한 딥러닝 시즌2 - TensorFlow

## LAB 12 - 0 RNN basic

In [3]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import Sequential, Model

print(tf.__version__)
tf.compat.v1.enable_eager_execution()

2.5.0


In [4]:
#one hot encoding
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

In [6]:
x_data = np.array([[h]], dtype=np.float32)

hidden_size = 2
#특정 셀을 선언하고 이를 loop
cell = layers.SimpleRNNCell(units=hidden_size)
rnn = layers.RNN(cell, return_sequences=True, return_state=True)
outputs, states = rnn(x_data)

#shape 값 잘 확인하기
print('x_data: {}, shape: {}'.format(x_data, x_data.shape))
print('outputs: {}, shape: {}'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]]], shape: (1, 1, 4)
outputs: [[[ 0.7390763  -0.36100665]]], shape: (1, 1, 2)
states: [[ 0.7390763  -0.36100665]], shape: (1, 2)


In [7]:
#위 두가지를 결합해 놓은 api 사용
rnn = layers.SimpleRNN(units=hidden_size, return_sequences=True, return_state=True)
outputs, states = rnn(x_data)

print('x_data: {}, shape: {}'.format(x_data, x_data.shape))
print('outputs: {}, shape: {}'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]]], shape: (1, 1, 4)
outputs: [[[-0.05069483  0.05460737]]], shape: (1, 1, 2)
states: [[-0.05069483  0.05460737]], shape: (1, 2)


In [8]:
x_data = np.array([[h, e, l, l, o]], dtype=np.float32)
#각각의 알파벳에 해당하는 원핫 벡터를 기반으로 시퀀스를 만들고 이를 rnn이 처리할 수 있도록 전처리
hidden_size = 2
rnn = layers.SimpleRNN(units=2, return_sequences=True, return_state=True)    
outputs, states = rnn(x_data)

print('x_data: {}, shape: {} \n'.format(x_data, x_data.shape))
print('outputs: {}, shape: {} \n'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]], shape: (1, 5, 4) 

outputs: [[[ 0.64205337 -0.60207236]
  [-0.40485123 -0.5271144 ]
  [ 0.7643618  -0.17918245]
  [ 0.15369034  0.5993915 ]
  [ 0.6612312  -0.22361602]]], shape: (1, 5, 2) 

states: [[ 0.6612312  -0.22361602]], shape: (1, 2)


### Batching Input

In [9]:
x_data = np.array([[h, e, l, l, o],
                   [e, o, l, l, l],
                   [l, l, e, e, l]], dtype=np.float32)
#미니배치 만들고

hidden_size = 2
rnn = layers.SimpleRNN(units=2, return_sequences=True, return_state=True)    
outputs, states = rnn(x_data)

print('x_data: {}, shape: {} \n'.format(x_data, x_data.shape))
print('outputs: {}, shape: {} \n'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]], shape: (3, 5, 4) 

outputs: [[[ 0.5109438   0.6131393 ]
  [ 0.8794135  -0.60768795]
  [-0.50782496 -0.07837684]
  [ 0.24852128  0.8221704 ]
  [ 0.63233584 -0.23692994]]

 [[ 0.70813584 -0.07490122]
  [-0.22535372 -0.46112406]
  [-0.1785148   0.7484225 ]
  [ 0.75784135  0.5817032 ]
  [ 0.556736   -0.21082743]]

 [[ 0.21827236  0.57209957]
  [ 0.6255398   0.3050802 ]
  [ 0.7809256  -0.6359473 ]
  [ 0.09495998 -0.605614  ]
  [-0.3714229   0.5962693 ]]], shape: (3, 5, 2) 

states: [[ 0.63233584 -0.23692994]
 [ 0.556736   -0.21082743]
 [-0.3714229   0.5962693 ]], shape: (3, 2)
